on:
  push:
    branches:
      - main
jobs:
  docusaurus-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          npm install
          cmd /C 'set "GIT_USER=ZHENG28" && yarn deploy'
