on:
  push:
    branches:
      - main
jobs:
  docusaurus-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
      - name: Deploy
        run: |
          npm install
          cmd /C 'set "GIT_USER=ZHENG28" && yarn deploy'
