on:
  push:
    branches:
      - main
jobs:
  docusaurus-deploy:
    runs-on: windows-latest
    steps:
      - run: |
          dir
          cd ..
          dir
          cd ..
          dir
          cmd /C 'set "GIT_USER=ZHENG28" && yarn deploy'
